global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'dbp-api'
    static_configs:
      - targets: ['host.docker.internal:8089'] # Si el API corre en el host
        # targets: ['api:8089'] # Si el API corre en la misma red de docker
    metrics_path: '/metrics'
