name: Docker Publish to GHCR

on:
  push:
    branches: [ "master", "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_API: ${{ github.repository_owner }}/dbp-api
  IMAGE_NAME_AGENT: ${{ github.repository_owner }}/dbp-agent

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker (API)
        id: meta-api
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_API }}
          tags: |
            type=raw,value=latest
            type=ref,event=branch

      - name: Build and push Docker image (API)
        uses: docker/build-push-action@v3
        with:
          context: ./api
          push: true
          tags: ${{ steps.meta-api.outputs.tags }}
          labels: ${{ steps.meta-api.outputs.labels }}

      - name: Extract metadata for Docker (Agent)
        id: meta-agent
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_AGENT }}
          tags: |
            type=raw,value=latest
            type=ref,event=branch

      - name: Build and push Docker image (Agent)
        uses: docker/build-push-action@v3
        with:
          context: ./agent
          push: true
          tags: ${{ steps.meta-agent.outputs.tags }}
          labels: ${{ steps.meta-agent.outputs.labels }}
